# Generated by Django 5.0.7 on 2026-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_booking_hours_used_booking_total_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_bg_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "login_bg_overlay",
                    models.FloatField(default=0.5, help_text="0.0 to 1.0"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
    ]
