# Generated by Django 5.0.7 on 2026-03-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Full name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email for notifications", max_length=254
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="Training/booking this person registered for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendee_set",
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee",
                "verbose_name_plural": "Attendees",
                "ordering": ["registered_at"],
                "unique_together": {("booking", "email")},
            },
        ),
    ]
